const GET_SIDEBAR_MENU = 'MENU/GET_SIDEBAR_MENU'
const GET_ROUTES = 'MENU/GET_ROUTES'
const WS_TEST = 'WS/TEST'
const WS_LIVESTREAM_APPEND = 'ws/livestream/append'
const WS_LIVESTREAM_DELETE = 'ws/livestream/delete'
const WS_LIVESTREAM_GET = 'ws/livestream/get'
const WS_LIVESTREAM_GET_TOTAL_COUNT = 'ws/livestream/get/total/count'
const WS_WAITALLUSERS_GET = 'ws/dental/wait/all/users/get'
const WS_WAITALLUSERS_APPEND = 'ws/dental/wait/all/users/append'
const WS_WAITUSER_WELCOME_GET = 'ws/dental/wait/welcome/get'
const WS_WAITUSER_WELCOME_SET = 'ws/dental/wait/welcome/set'
const WS_WAITUSER_CURRENT_GET = 'ws/dental/wait/current'
const GET_DOCTOR_MEMBERS = 'DOCTOR/MEMBERS'
const GET_EDENT_ITEMS = 'EDENT/ITEMS'
const GET_EDENT_HEADERS = 'EDENT/HEADERS'
const GET_BITCOIN_RECENT_TRANSACTIONS = 'BITCOIN/RECENT_TRANSACTIONS'

const SIDENAV_DRAWER = 'SIDENAV_DRAWER'
const LOGIN_STATUS = 'LOGIN_STATUS'
const CART_ITEMS = 'CART_ITEMS'
const CART_ITEMS_COUNT = 'CART_ITEMS_COUNT'

export default {
  GET_SIDEBAR_MENU,
  GET_ROUTES,
  WS_TEST,
  WS_LIVESTREAM_APPEND,
  WS_LIVESTREAM_DELETE,
  WS_LIVESTREAM_GET,
  WS_LIVESTREAM_GET_TOTAL_COUNT,
  WS_WAITALLUSERS_GET,
  WS_WAITALLUSERS_APPEND,
  WS_WAITUSER_WELCOME_GET,
  WS_WAITUSER_WELCOME_SET,
  WS_WAITUSER_CURRENT_GET,
  GET_DOCTOR_MEMBERS,
  GET_EDENT_ITEMS,
  GET_EDENT_HEADERS,
  GET_BITCOIN_RECENT_TRANSACTIONS,
  SIDENAV_DRAWER,
  LOGIN_STATUS,
  CART_ITEMS,
  CART_ITEMS_COUNT
}
